#include <iostream>
#include <iomanip>
#include <cstdlib>
#include <ctime>

using namespace std;

int main(){
/*
for (int i = 1; i < 5; i++){

 cout << "Enter Your inc : " << i << "\n";
}
int cond;
cout << "Enter  Your Condition : ";
cin >> cond;
for (int i = 0; i < cond; i++){
    cout << "Your Inc Is :" << i << "\n";
}*/

/*
int cond;
cout << "Enter Your condition : ";
cin >> cond;

for (int y = 1; y < cond; y = y + 2){

    cout<<"The inc is : " << y << "\n";
}*/



/*
int cond;
cout <<"Enter Your Condition :";
cin >> cond;

for (int i =0; i< cond; i++){
   if (i == 5){
        break;
   }
    cout <<"Increament is : " << i <<"\n";
}

int cond2;
cout <<"Enter Your Condition :";
cin >> cond2;

for (int y =0; y< cond2; y++){
   if (y == 5){
        continue;
   }
    cout <<"Increament is : " << y <<"\n";
}



int Num;
cout <<"Enter Your Number : ";
cin >> Num;

for (int cond = 0; cond <= Num; cond++){
    cout << "Your Loop Is : "<< cond<<"\n";

    if (cond == 4){
        break;
    }
}*/

/*
int num;
cout << "ENter Your Number : ";
cin >> num;

int cond;
cout <<"Enter Your Condition : ";
cin >> cond;

while(cond <= num ){
  cond++;

    if(cond == 5){
        continue;
    }
    cout << "The While Loop Condition is  : "<< cond << "\n";

}*/








/*
int numbers[] = {5,8,9,2,50};

for (int i=1; i < 6; i++){
    cout << i << " = " << numbers[i] << "\n";
}

return 0;
}*/



/*

int calculatePower(int, int);

int main()
{
    int base, powerRaised, result;

    cout << "Enter base number: ";
    cin >> base;

    cout << "Enter power number(positive integer): ";
    cin >> powerRaised;

    result = calculatePower(base, powerRaised);
    cout << base << "^" << powerRaised << " = " << result;

    return 0;
}

int calculatePower(int base, int powerRaised)
{
    if (powerRaised != 0)
        return (base*calculatePower(base, powerRaised-1));
    else
        return 1;
}*/




/*
int calburnedday;
int calburnedweek = 0;
int days = 0;
double average;

while (days <= 3)
{
    cout << "Enter the days burned : ";
    cin >> calburnedday;
    cout << endl;

    calburnedweek = calburnedweek + calburnedday;
    cout << "from days :" << days << " = " << calburnedday;
    cout << endl;
    days ++;
}

average = calburnedweek/3;

cout << "The Average is : " << average;
cout << endl;
*/







/*

string Name;
int NumberOfVolunteers;
int NumberOfBoxSold;
int TotalNumberOfBoxSold = 0;
double CostOfOneBox;

int counter = 0;

//about this line make sure to insert the #include <iomanip> on top of the code
cout << fixed << showpoint << setprecision(2);

cout << "Enter The Numbers Of Volunteers ";
cin >> NumberOfVolunteers;
cout << endl;

while (counter < NumberOfVolunteers)
{
    cout << "Enter The Volunteers Name and Number of Boxes Sold : ";
    cin >> Name >> NumberOfBoxSold;
    TotalNumberOfBoxSold = TotalNumberOfBoxSold + NumberOfBoxSold;
    counter++;
}

cout << "The Total of the vox sold is : " << TotalNumberOfBoxSold;
cout << endl;

cout << "Enter The Cost of each Boxes : ";
cin >> CostOfOneBox;
cout << endl;

cout << "Total of each sudent boxes time the Price of the numbers of box holding : ";
cout << "Total : " << "R"<< TotalNumberOfBoxSold * CostOfOneBox;
cout <<endl;

if(counter != 0 )
{
    cout << "the average of each soldboxes made by the student volunteers : ";
    cout << TotalNumberOfBoxSold / counter;
    cout << endl;
}
else{
    cout << "No Input ";
}
*/








//Student at the midle school volunteered to sell fresh backed cookies to raise funds to increase the number of the computer lab
// each student reported the number of boxes sold. we will write  aprogram that will output the total number of boxes of cookies sold,the total revenue
//generated by the selling the cookies,and the average of number of the boxes sold by each student in the following form:
//StudentName, NumberOf Boxes
/*

int Student_Volunteer;
string StudentName;
int NumberOfBoxes;
double TotalRevenue =0;

int Cookies_cost;
int counter = 0;


cout << fixed << showpoint << setprecision(2);
cout << "Enter The Number of the Student Volunteers : ";
cin >> Student_Volunteer;
cout <<endl;


while (counter < Student_Volunteer)
{
    cout << "Enter The Student Name : ";
    cin >> StudentName;
    cout <<endl;
    cout << "Enter The Student Number Of Boxes They  hold : ";
    cin >> NumberOfBoxes;
    cout << endl;

    TotalRevenue = TotalRevenue + NumberOfBoxes;
    cout << "The Name is " << StudentName <<endl;
    cout << "The Number of Boxes are : " << NumberOfBoxes << endl << endl;


    cout << "Enter Another Name : \n";

    counter++;
}


    cout << "Total revenu : " << TotalRevenue <<endl;

    cout << "Enter The Cost Of each student box :";
    cin >> Cookies_cost;
    cout << endl;

    cout << "The total of each student box sold : " << TotalRevenue * Cookies_cost;
    cout <<endl;

    if(counter != 0 )
    {
        cout << "The Tota Revenue of each student Average is : " << TotalRevenue / counter;
        cout << endl;
    }
    else {
        cout << "Wrong input ";
        cout << endl;
    }

    */





/*
    //this program is guessing the number  from 1 to 100
    int number;
    int guess;
    int numbeOfGuess_Limitation = 1;
    //you need to include this so that it gonna be randomly otherwise it will jus guess same number
    //and for the to work u include this sentence at the top #include <ctime>
     srand(time(0));
     //for this to work u have to include this #include <cstdlib> at the top of the code
    number = rand() % 100;
      cout <<" THE GAME BEGGIN! \n\n";

    while ((numbeOfGuess_Limitation < 10) && (number != guess))
    {
        cout <<" try To guess from 1 to 100 :\n";
        cin >> guess;
        cout << endl;

        if(guess == number)
        {
            cout << "You guess it congrate lation you have won! \n";
            break;
        }

        else if(guess < number )
        {
            cout << "go up \n";
        }

        else {
            cout <<"go down \n";
        }


         if(numbeOfGuess_Limitation == 8){

        cout << endl;
        cout << "You have loosed! the correct number is : " << number << endl;
        break;
   }

  numbeOfGuess_Limitation++;
   } //end while

*/

/*
double sum =0;
double NewNumber;
double average;


for (int i = 0; i< 5; i++)
{

    cout << "Enter New Number : \n\n";
    cin >> NewNumber;
    cout << endl;
    sum = sum + NewNumber;

}

cout << "The Sum of all the number insert are : " << sum;
cout <<endl;


average = sum / 5;
cout << "The Average is : " << average;
cout <<endl;
*/







/*
int sum,num;



for(int i=0; i< 4; i++){

    sum =0;

    for(int j=0; j< 4; j++)
    {
        cin >> num;
        cout << endl;

        sum = sum + num;
    }

     cout << "sum = " << sum;
     cout <<endl;

}
*/






/*
//this program it ask the user to Enter Y or y to Enter two number and display the sum of those two number
//then ask again the two enter 2 number then display the sum
char respond;
double num1,num2, sum;

cout <<"Enter Letter Y ir y :\n\n";
cin >> respond;

int counter = 1;
while (counter < 3)
{

    if(respond == 'Y' || respond =='y')
    {
    cout << "Enter Num1 And Num2 :";
    cin >> num1 >> num2;
    cout <<endl;

    sum = num1 + num2;
    cout <<"the sum is :" << sum <<"\n";

    }

    else if (respond != 'Y' || respond != 'y'){

    cout << "Enter Num1 And Num2 :";
    cin >> num1 >> num2;
    cout <<endl;

    sum = num1 + num2;
    cout <<"the sum is :" << sum;
    break;
    }
 counter++;
}

*/




/*
int num1,num2,sum;
char respont;
cout << "Insert Letter Y or y : \n\n";
cin >> respont;

while (respont == 'Y' || respont == 'y')
{

    cout << " Insert num1 and num2 : ";
    cin >> num1 >> num2;
    cout <<endl;
    sum = num1 + num2;
    cout << "The Sum of this two number is : " << sum;
    cout << endl;


if(respont == 'Y' || respont == 'y')
    {

    cout << " Insert num1 and num2 : ";
    cin >> num1 >> num2;
    cout <<endl;
    sum = num1 + num2;
    cout << "The Sum of this two number is : " << sum;
    cout << endl;

    }


    else if (respont != true){
    break;

    }

}
*/



/*
int total =0, counte=0, number;

do{

    cout << "Enter The number : ";
    cin >> number;
    total = total+number;
    counte++;
}
while (counte != 2);


cout << "The sum of the number is : " << total << endl;


*/



/*
int total =0, counte=0, number;

cout <<" Insert the number : ";
cin >> number;

while ( counte != 3)
{
    cout <<" Insert the number : ";
    cin >> number;
    total = total + number;

    counte++;
}
cout << "The total is : " << total;
cout <<endl;
*/


/*
for(int i=0; i< 3; i++)
{
    for(int j =0; j< 5; j++)
    {
        //setw(6) just means margin-right of 6
        cout << setw(6) << i;
        cout << endl;
    }
}
*/
/*
for(int i=0; i< 2; i++)
{
    for(int j =0; j< 5; j++)
    {

        //setw(6) just means margin-right of 6
        cout << setw(6) << j;
       // cout << endl;
    }
    cout <<endl;
}
return 0;
}
*/
